apiVersion: v1
kind: Service
metadata:
  name: github-actions-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: github-actions-exporter
    app.kubernetes.io/component: monitoring
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9999
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: github-actions-exporter
