apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-backups
  namespace: monitoring
  labels:
    app.kubernetes.io/name: pg-backup
    app.kubernetes.io/component: backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-kubernetes
  resources:
    requests:
      storage: 5Gi
