apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gitlab
  namespace: gitlab-runner
spec:
  interval: 24h
  url: http://nexus-nexus-repository-manager.nexus.svc.cluster.local:8081/repository/helm-gitlab/
