apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gitlab
  namespace: gitlab
  labels:
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gitlab
  endpoints:
    - port: http
      path: /-/metrics
      interval: 60s
