apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: podinfo
spec:
  interval: 5m
  url: http://nexus-nexus-repository-manager.nexus.svc.cluster.local:8081/repository/helm-podinfo/