apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: windmill-secrets
  namespace: windmill
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: windmill-secrets
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: Windmill
        property: db-connection-url
