apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 24h
  url: http://nexus-nexus-repository-manager.nexus.svc.cluster.local:8081/repository/helm-longhorn/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: longhorn
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: longhorn-system
      interval: 12h
  values:
    defaultSettings:
      defaultReplicaCount: 2
      defaultDataLocality: best-effort
      storageMinimalAvailablePercentage: 15
      defaultLonghornStaticStorageClass: longhorn
    persistence:
      defaultClassReplicaCount: 2
      defaultClass: false
    ingress:
      enabled: false
