---
apiVersion: v1
kind: Namespace
metadata:
  name: portainer
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 24h
  url: http://nexus-nexus-repository-manager.nexus.svc.cluster.local:8081/repository/helm-portainer/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 30m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: portainer
      version: "2.x"
      sourceRef:
        kind: HelmRepository
        name: portainer
        namespace: portainer
      interval: 12h
  values:
    localMgmt: true
    tls:
      force: false
    service:
      type: ClusterIP
    persistence:
      enabled: true
      storageClass: nfs-kubernetes
      size: 2Gi
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        cert-manager.io/cluster-issuer: homelab-ca-issuer
        nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.oauth2-proxy.svc.cluster.local/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://oauth2-proxy.10.0.0.201.nip.io/oauth2/start?rd=$scheme://$host$request_uri"
        nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Access-Token"
      hosts:
        - host: portainer.10.0.0.201.nip.io
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: portainer-tls
          hosts:
            - portainer.10.0.0.201.nip.io
