apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  # namespace is set to podinfo-staging by the kustomization namespace field
  labels:
    app.kubernetes.io/name: podinfo
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 20s
