apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-movies
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.0.0.161
    path: /volume1/videos/Movies
    readOnly: true
  claimRef:
    name: plex-movies
    namespace: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-movies
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: plex-movies
  resources:
    requests:
      storage: 1Ti
