apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-photos
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.0.0.161
    path: /volume1/photos
    readOnly: true
  claimRef:
    name: plex-photos
    namespace: media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-photos
  namespace: media
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  volumeName: plex-photos
  resources:
    requests:
      storage: 500Gi
