---
apiVersion: v1
kind: Namespace
metadata:
  name: velero
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: minio
  namespace: velero
spec:
  interval: 24h
  url: http://nexus-nexus-repository-manager.nexus.svc.cluster.local:8081/repository/helm-minio/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
  namespace: velero
spec:
  interval: 1h
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: minio
      version: "5.x"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: velero
      interval: 12h
  values:
    mode: standalone
    replicas: 1
    persistence:
      enabled: true
      storageClass: "nfs-kubernetes"
      size: 50Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi
    existingSecret: minio-credentials
    buckets:
      - name: velero-backups
        policy: none
        purge: false
    ingress:
      enabled: false
    consoleIngress:
      enabled: false
