apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: teamcity
resources:
  - namespace.yaml
  - external-secret.yaml
  - server-pvc.yaml
  - server-deployment.yaml
  - server-service.yaml
  - ingress.yaml
  - tailscale-ingress.yaml
  - agents-statefulset.yaml
  - agents-service.yaml
  - cargo-config.yaml
