apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: coder-secrets
  namespace: coder
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: coder-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-connection-url
      remoteRef:
        key: Coder
        property: db-connection-url
